### ISSUE TITLE
SQL-Datenbank aufsetzen

### ISSUE THREAD

**Issue by liviawelschinger** [liviawelschinger/digitaler-einkauf#4]
DB-Schema

- Produktkategorien
- Produkte: Preis, Auswahl Anzahl
- Bestellung speichern
- Voraussetzung, dass eine Bestellung den Status Offen erhält ist die vorgelagerte Bezahlung der ausgewählten Produkte
- Bestellstatus: Offen, Kommissionierer zugewiesen, In Bearbeitung, Bereit zur Abholung / Bereit zur Auslieferung, Ausgeliefert, Zurückgenommen (Sonderstatus z.B. weil die Bestellung fälschlicherweise aufgegeben wurde)

Ein Kommissionierer kann nur einem Supermarkt zugeordnet, ein Supermarkt kann mehrere Supermärkte beschäftigen
Kommissionierer fragt nach den Pull-Prinzip die Lieferfähigkeit bei Supermärkten in der Nähe an 
Umkreis festlegen (Umkreisssuche durch Google Maps)

**SQL-Datenbank (Liquibase: https://www.liquibase.org/)**

**Comment by malex5335** [comment]
ER-Modell: https://dbdiagram.io/d/5e75413e4495b02c3b888b15

**Comment by malex5335** [comment]
- [ ]  ER-Modell anpassen
- [ ] Liquibase integrieren
- [ ] Enteties aktualisieren
